### ISSUE TITLE
Broken go mod tidy

### ISSUE THREAD

**Issue by neurlang** [xlab/linmath#1]
Could this import path be fixed? It breaks go mod.

```
	native "github.com/xlab/linmath-go/linmath"
```

to
```
	native "github.com/xlab/linmath"
```

**Comment by timohuovinen** [comment]
I see the same error

**Comment by xlab** [comment]
Just realized that those tests were testing the port against `linmath-go` which was a CGo wrapper over native implementations, and I forgot to commit that wrapper in 2017 - had it on my disk in GOPATH, so import worked.

For now, I am removing the test. Will re-create wrapper some day and add test back.

Also, added Go mod file, so this lib is mod-friendly now.
